### ISSUE TITLE
what is the point of this package?

### ISSUE THREAD

**Issue by randomgambit** [romainfrancois/dance#48]
HI @romainfrancois I am a huge fan of your work, but here I have a hard time understanding what is the point of this package. Is this a complement to `dplyr`? a possible replacement? 

Thanks!

**Comment by romainfrancois** [comment]
- experimenting 🤹‍♂️ on features and approaches outside of the `dplyr` fortress 🏰 
  - have fun using the dancing related words and concepts 💃 👯‍♂️ 
  - engage the community on a low stakes 📦 which gives plenty of learning opportunities on twitter or live perhaps at a meetup/hackaton/unconf 👩‍💻
  - have an excuse to unleash bunch of dancing gifs on twitter 🕺🤖
  - why not ❓
  - because it's there 🤪
  - what's the point of anything really ?
